# Imports

In [1]:
import gzip
import pandas as pd
from collections import Counter
import string
from collections import defaultdict
from bs4 import BeautifulSoup
import requests
import langid
import sys
from glob import glob
import os
import pickle
from tqdm import tqdm
import numpy as np
import random
import re, string
from glob import glob


STOPWORDS = set(['and','not','of','the'])

In [2]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import SnowballStemmer
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('stopwords')
#for model-building
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, f1_score, accuracy_score, confusion_matrix
from sklearn.metrics import roc_curve, auc, roc_auc_score
# bag of words
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
#for word embedding
import joblib
from sklearn.calibration import calibration_curve, CalibratedClassifierCV
pd.set_option("max_colwidth", None)
import spacy
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score
from sentence_transformers import SentenceTransformer


def preprocess(text):
    text = text.lower() 
    text=text.strip()  
    text=re.compile('<.*?>').sub('', text) 
    text = re.compile('[%s]' % re.escape(string.punctuation)).sub(' ', text)  
    text = re.sub(r'\s+', ' ', text)  
    text = re.sub(r'\[[0-9]*\]',' ',text) 
    text=re.sub(r'[^\w\s]', '', str(text).lower().strip())
    text = re.sub(r'\d',' ',text) 
    text = re.sub(r'\s+',' ',text) 
    return text

# STOPWORD REMOVAL
def stopword(x):
    a= [i for i in x.split() if i not in stopwords.words('english')]
    return ' '.join(a)
#LEMMATIZATION
# Initialize the lemmatizer
wl = WordNetLemmatizer()
 
# This is a helper function to map NTLK position tags
def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN
# Tokenize the sentence
def lemmatizer(x):
    word_pos_tags = nltk.pos_tag(word_tokenize(x)) # Get position tags
    a=[wl.lemmatize(tag[0], get_wordnet_pos(tag[1])) for idx, tag in enumerate(word_pos_tags)] # Map the position tag and lemmatize the word/token
    return " ".join(a)


def finalpreprocess(x):
    return lemmatizer(stopword(preprocess(x)))

def return_linear_clf(name,data,preproc_fun, target_field= "is_STEM"):
    print("Preprocessed the datasets...")

    df_dept_vector = preproc_fun(data['fieldname'].values.tolist())
    X_train = df_dept_vector
    y_train = data[target_field].astype(int)
    base_clf = LogisticRegression(random_state=0)
    clf = CalibratedClassifierCV(base_clf, cv=5).fit(X_train, y_train)
    print("Trained model...")

    return name,clf,-1,-1,-1


def avg_emb_preproc(names):
    return np.asarray([nlp(x).vector for x in names], dtype="object")


def simcse_preproc(names,device_name="cpu"):
    return model.encode(names,
                          device=device_name,
                          batch_size=100, 
                          convert_to_numpy=True)

[nltk_data] Downloading package punkt to
[nltk_data]     /home/csefaculty/kjoseph/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/csefaculty/kjoseph/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /home/csefaculty/kjoseph/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/csefaculty/kjoseph/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Model Training

In [3]:
nlp = spacy.load("en_core_web_md")
model = SentenceTransformer("princeton-nlp/sup-simcse-roberta-large")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 391/391 [00:00<00:00, 30704.20it/s]
RobertaModel LOAD REPORT from: princeton-nlp/sup-simcse-roberta-large
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

### Load in Data from Larremore study

In [4]:
df_dept = pd.read_csv('data/larremore_field_data.csv')
df_dept = df_dept.dropna(subset=['DepartmentName', 'is_STEM'])

print(len(df_dept))

df_dept['orig_cleaned'] = df_dept['DepartmentName'].apply(lambda x: finalpreprocess(x))
df_dept['simple_cleaned'] = df_dept['DepartmentName'].str.replace(", (Graduate )?(Department|School|Institute|Division|College) of$","",regex=True)

6119

In [5]:
df_dept.head()

,DepartmentName,Field,Area,Umbrella,is_STEM,orig_cleaned,simple_cleaned
0,"Mathematics, School of",Mathematics,Mathematical Sciences,Mathematics and Computing,True,mathematics school,Mathematics
1,"Mathematics, Department of",Mathematics,Mathematical Sciences,Mathematics and Computing,True,mathematics department,Mathematics
2,"Psychology, School of",Psychology,Psychological Sciences,Social Sciences,False,psychology school,Psychology
3,"Biology, Department of",Biological Sciences,Biological Sciences,Natural Sciences,True,biology department,Biology
4,"Psychological Sciences, Department of",Psychology,Psychological Sciences,Social Sciences,False,psychological science department,Psychological Sciences

In [6]:
name_cols = ['orig_cleaned','simple_cleaned','Field','Area','Umbrella']

In [7]:
dat = []
for x in name_cols:
    named_df = df_dept[[x,'is_STEM']].rename(columns={x:"fieldname"})
    named_df['ty'] = x
    dat.append(named_df)
fld = pd.concat(dat, ignore_index=True).drop_duplicates()
k = fld.groupby("fieldname").size()
k[k >1].index[:5]

Index(['Accounting', 'Accounting and Information Systems',
       'Accounting, Finance and Information Systems', 'Advanced Structures',
       'Aerospace Engineering'],
      dtype='str', name='fieldname')

In [8]:
# Toss things not labeled STEM/Not-STEM or things labeled both STEM/Not STEM
fld = fld[~fld.fieldname.isin(k[k>1].index.values)] 
fld = fld[pd.notnull(fld.fieldname)]

In [9]:
fld.sample(3)

,fieldname,is_STEM,ty
1864,plant science school,True,orig_cleaned
5653,engineering technology survey engineering department,True,orig_cleaned
4331,write rhetoric study department,False,orig_cleaned

### Load in ORCID labeled training data

In [10]:
orcid_training = pd.read_csv("data/stem_training_data.csv",sep="\t")
print(orcid_training.groupby(['error in translation?']).n.sum())
orcid_training = orcid_training.loc[orcid_training['error in translation?'] == 0,:]
orcid_training.loc[:,'is_STEM'] = orcid_training['stem?'] == 1

m = orcid_training[['cmd','is_STEM']]
m.columns = ['fieldname','is_STEM']
m.loc[:,'ty'] = 'manual'
m.loc[:,'fieldname'] = m['fieldname'].str.replace("(Graduate )?(Department|School|Institute|Division|College) of ","",regex=True,flags=re.I)
fld = pd.concat([fld,m],axis=0)

error in translation?
0    1259313
1      64860
Name: n, dtype: int64

### Build models

In [11]:
res = []
for preproc_fun in [simcse_preproc]:#avg_emb_preproc,
    for fieldlist in [ ['orig_cleaned'],
                       ['simple_cleaned'],
                       ['simple_cleaned','manual'],
                       ['orig_cleaned','Field','Area','Umbrella'],
                       ['simple_cleaned','Field','Area','Umbrella']]:
        name= "_".join(fieldlist)+"_"+preproc_fun.__name__
        print(name)
        res.append(return_linear_clf(name,fld[fld.ty.isin(fieldlist)],preproc_fun))

orig_cleaned_simcse_preproc
Preprocessed the datasets...

/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Trained model...
simple_cleaned_simcse_preproc
Preprocessed the datasets...

/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Trained model...
simple_cleaned_manual_simcse_preproc
Preprocessed the datasets...

/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Trained model...
orig_cleaned_Field_Area_Umbrella_simcse_preproc
Preprocessed the datasets...

/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Trained model...
simple_cleaned_Field_Area_Umbrella_simcse_preproc
Preprocessed the datasets...

/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/data/kjoseph/miniconda3/envs/orcid_gep/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Trained model...

## Validate and Test

In [12]:
validation_data = pd.read_csv("data/stem_validation_data.csv")
validation_data.shape

(250, 3)

In [13]:
validation_data.head()

                      cmd  stem final  medicine final
0               chemistry           1               0
1                 physics           1               0
2              psychology           0               0
3                medicine           1               1
4  mechanical engineering           1               0

In [14]:
from sklearn.metrics import precision_recall_curve,classification_report
pd.options.mode.chained_assignment = None 
for name, clf in [(v[0],v[1]) for v in res]:
    print(name)
    if 'avg_emb' in name:
        embs = avg_emb_preproc(validation_data.cmd.values.tolist())
    else:
        embs = simcse_preproc(validation_data.cmd.values.tolist())
    validation_data[name] =  clf.predict_proba(embs)[:, 1]
    print(classification_report(validation_data['stem final'],validation_data[name] > .5))

orig_cleaned_simcse_preproc
              precision    recall  f1-score   support

           0       0.86      0.90      0.88       113
           1       0.92      0.88      0.90       137

    accuracy                           0.89       250
   macro avg       0.89      0.89      0.89       250
weighted avg       0.89      0.89      0.89       250

simple_cleaned_simcse_preproc
              precision    recall  f1-score   support

           0       0.86      0.90      0.88       113
           1       0.92      0.88      0.90       137

    accuracy                           0.89       250
   macro avg       0.89      0.89      0.89       250
weighted avg       0.89      0.89      0.89       250

simple_cleaned_manual_simcse_preproc
              precision    recall  f1-score   support

           0       0.85      0.91      0.88       113
           1       0.92      0.87      0.89       137

    accuracy                           0.89       250
   macro avg       0.89      0.89      0.89       250
weighted avg       0.89      0.89      0.89       250

orig_cleaned_Field_Area_Umbrella_simcse_preproc
              precision    recall  f1-score   support

           0       0.88      0.88      0.88       113
           1       0.90      0.90      0.90       137

    accuracy                           0.89       250
   macro avg       0.89      0.89      0.89       250
weighted avg       0.89      0.89      0.89       250

simple_cleaned_Field_Area_Umbrella_simcse_preproc
              precision    recall  f1-score   support

           0       0.86      0.89      0.87       113
           1       0.91      0.88      0.89       137

    accuracy                           0.88       250
   macro avg       0.88      0.88      0.88       250
weighted avg       0.89      0.88      0.88       250

In [15]:
name = 'simple_cleaned_manual_simcse_preproc'
validation_data[(validation_data['stem final'] == 0) & (validation_data[name] > .5)][['cmd',name]]

,cmd,simple_cleaned_manual_simcse_preproc
120,viticulture and enology,0.876896
129,conservation department,0.879447
157,aquatic animal health management,0.920379
172,mrc social genetic and developmental psychiatry centre,0.680015
173,rolling mill,0.647922
178,maritime transportation,0.533456
192,esilv,0.911741
206,mine building and underground structures,0.665846
212,gradaute program in neuroscience,0.726643
248,centralized monitoring solutions,0.746036

In [16]:
name = 'simple_cleaned_manual_simcse_preproc'
validation_data[(validation_data['stem final'] == 1) & (validation_data[name] < .5)][['cmd',name]]

,cmd,simple_cleaned_manual_simcse_preproc
45,dentistry,0.284705
63,emergency medicine,0.294647
75,emergency department,0.104189
84,applied science,0.476092
89,audiology,0.102921
111,head and neck surgery,0.357249
122,technical faculty,0.353919
148,hospital de clínicas,0.309923
149,forensic and applied sciences,0.479183
159,anesthesia and intensive care unit,0.142893
161,inibioma,0.068068
167,faculty science,0.181920
170,artificial inteligence,0.339934
180,geography &amp; spatial planning,0.002441
187,science and higher education,0.029831
203,"\""alexandra\"" hospital, 1st ob/gyn department",0.152879
213,discovery research and development,0.209280
229,orthodontic professional committee,0.477217

# Save best model

In [17]:
import joblib

clf =[x[1] for x in res if x[0] == 'simple_cleaned_manual_simcse_preproc'][0]
# Save the model
joblib.dump(clf, 'data/final_stem_classifier.joblib')

['data/final_stem_classifier.joblib']

# Assess STEM Classifier

In [19]:
model = SentenceTransformer("princeton-nlp/sup-simcse-roberta-large")
x = df_dept.simple_cleaned.tolist()
embs = simcse_preproc(x)
df_dept['preds'] = clf.predict_proba(embs)[:, 1]

Loading weights: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 391/391 [00:00<00:00, 29404.95it/s]
RobertaModel LOAD REPORT from: princeton-nlp/sup-simcse-roberta-large
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [23]:
df_dept[['simple_cleaned','Field','is_STEM','preds']].drop_duplicates().to_csv("robustness/spoon_data_robustness_check.csv",index=False)